### ISSUE TITLE
Test API for weather

### ISSUE THREAD

**Issue by troy-earle** [troy-earle/Project-1-GB#3]
Tested APIs using postman for validation of data and wether by location

![Image](https://user-images.githubusercontent.com/17156135/228177434-908291a1-b3a0-441a-a0d9-fe3aff161939.png)

![Image](https://user-images.githubusercontent.com/17156135/228176358-9bed38fb-dc97-458a-8086-ea60ef9faebc.png)

**Comment by troy-earle** [comment]
@karra-ormsby Please Review and validate

**Comment by karra-ormsby** [comment]
Reviewed
