### ISSUE TITLE
Find alternative CSS framework

### ISSUE THREAD

**Issue by troy-earle** [troy-earle/Project-1-GB#8]
Find and alternative framework to bootstrap for CSS

https://materializecss.com

CDN
(
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>)

**Comment by karra-ormsby** [comment]
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

to get the images
